#!/bin/bash
# Install KickOS
# B.Titze 2021
# KickOS updater

sudo rm -rf /home/$USER/KickOS/
sudo rm -rf /home/$USER/.KickOS/
cd
#sudo apt -y upgrade
git clone --depth=1 https://github.com/Jodels2002/KickOS.git

sudo chmod -R 777 KickOS
cd /home/pi/KickOS/scripts/
./pikickme.sh

   
